#!/usr/bin/env node
/**
 * Squad Scaffold - Creates directory structure for new squads.
 *
 * Usage:
 *   node scaffold-squad.cjs <slug> [--name "Display Name"]
 *   node scaffold-squad.cjs  # Uses .aiox/squad-runtime/active-squad.json
 *
 * Creates:
 *   squads/{slug}/
 *   ├── agents/
 *   ├── tasks/
 *   ├── templates/
 *   ├── data/
 *   ├── checklists/
 *   ├── docs/
 *   ├── scripts/
 *   ├── config.yaml
 *   └── README.md
 */

const fs = require('fs');
const path = require('path');
const {
  DEFAULT_WORKFLOW,
  readActiveSquad: readActiveSquadFromRuntime,
  readStateWithLegacyFallback,
} = require(path.join(__dirname, 'lib', 'squad-runtime-paths.cjs'));

// ═══════════════════════════════════════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════════════════════════════════════

const SQUADS_BASE = path.resolve(__dirname, '..', '..'); // squads/

const DIRECTORIES = [
  'agents',
  'tasks',
  'templates',
  'data',
  'checklists',
  'docs',
  'scripts'
];

const WORKSPACE_LEVELS = new Set(['none', 'read_only', 'controlled_runtime_consumer', 'workspace_first']);

function hasWorkspaceGovernanceSquad() {
  return fs.existsSync(path.join(SQUADS_BASE, 'c-level'));
}

// ═══════════════════════════════════════════════════════════════════════════
// TEMPLATES
// ═══════════════════════════════════════════════════════════════════════════

function getReadmeTemplate(slug, displayName, date, workspaceLevel) {
  return `# ${displayName} Squad

**Status:** 🚧 In Development
**Created:** ${date}
**Workspace Integration Level:** \`${workspaceLevel}\`

---

## Overview

*Description pending - update after research phase*

---

## Agents

| Agent | Role | Status |
|-------|------|--------|
| TBD | TBD | 📋 Planned |

---

## Quick Start

\`\`\`bash
# Validate squad structure
python3 squads/squad-creator/scripts/validate-squad-structure.py squads/${slug}

# View squad analytics
python3 squads/squad-creator/scripts/squad-analytics.py --squad ${slug}
\`\`\`

---

## Structure

| Directory | Purpose |
|-----------|---------|
| \`agents/\` | Agent definitions |
| \`tasks/\` | Task workflows |
| \`templates/\` | Reusable templates |
| \`data/\` | Knowledge base, frameworks |
| \`checklists/\` | Validation checklists |
| \`docs/\` | Squad documentation |
| \`scripts/\` | Utility scripts |

## Workspace Integration Contract

- \`workspace_integration.level\`: \`${workspaceLevel}\`
- \`workspace_integration.rationale\`: PENDING (must be defined before production)
- \`workspace_integration.read_paths\`: PENDING
- \`workspace_integration.write_paths\`: PENDING
- \`workspace_integration.template_namespace\`: PENDING

---

## Pipeline Progress

Check current state:

\`\`\`bash
node squads/squad-creator/scripts/squad-state-manager.cjs get ${slug}
\`\`\`

---

*Generated by squad-creator pipeline*
`;
}

function getConfigTemplate(slug, displayName, date, workspaceLevel) {
  return `# ${displayName} Squad Configuration
# Generated: ${date}

squad:
  slug: ${slug}
  display_name: "${displayName}"
  created_at: "${date}"
  status: in_development

metadata:
  source_mind: null
  target_domain: null
  description: null

workspace_integration:
  level: ${workspaceLevel}
  rationale: "PENDING - define why this level is required"
  read_paths: []
  write_paths: []
  template_namespace: null

# Agent definitions (populated during scaffolding phase)
agents: []

# Task definitions (populated during task anatomy phase)
tasks: []

# Quality gates
quality:
  checkpoint_required: true
  checkpoint_phase: quality_gate

# Pipeline configuration
pipeline:
  workflow: create-squad
  current_phase: init
`;
}

// ═══════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════

function outputJson(data) {
  console.log(JSON.stringify(data));
}

function outputError(code, message, details = {}) {
  outputJson({ success: false, error: { code, message, details } });
}

function resolveSlug(cliSlug) {
  if (cliSlug && !cliSlug.startsWith('-')) return cliSlug;
  const positional = process.argv.slice(2).find(a => !a.startsWith('-'));
  if (positional) return positional;
  return readActiveSquadFromRuntime();
}

function readState(slug) {
  const result = readStateWithLegacyFallback(slug, {
    workflow: DEFAULT_WORKFLOW,
  });
  if (!result.state || result.state.__corrupted) return null;
  return result.state;
}

function parseArg(args, flag) {
  const idx = args.indexOf(flag);
  if (idx === -1 || idx + 1 >= args.length) return null;
  return args[idx + 1];
}

// ═══════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════

function main() {
  const args = process.argv.slice(2);

  if (args[0] === '--help' || args[0] === '-h') {
    console.log(`Squad Scaffold - Creates directory structure for new squads

Usage:
  node scaffold-squad.cjs <slug> [--name "Display Name"]
  node scaffold-squad.cjs  # Uses .aiox/squad-runtime/active-squad.json

Options:
  --name "Name"    Display name for the squad (default: slug title-cased)
  --workspace-level <none|read_only|controlled_runtime_consumer|workspace_first>
                    Required integration level with workspace (default: read_only)

Creates directories: ${DIRECTORIES.join(', ')}
Creates files: README.md, config.yaml`);
    process.exit(0);
  }

  // Resolve slug
  const cliSlug = args[0];
  const slug = resolveSlug(cliSlug);

  if (!slug) {
    outputError('NO_SLUG', 'No slug provided and no active squad pointer found', {
      hint: 'Run: node squad-state-manager.cjs init <slug> first'
    });
    process.exit(1);
  }

  // Validate slug format
  if (!/^[a-z0-9]+(_[a-z0-9]+)*$/.test(slug)) {
    outputError('INVALID_SLUG', 'Slug must be snake_case', {
      received: slug,
      expected_pattern: '^[a-z0-9]+(_[a-z0-9]+)*$'
    });
    process.exit(1);
  }

  // Get display name from args or state or derive from slug
  const state = readState(slug);
  const argName = parseArg(args, '--name');
  const workspaceLevel = parseArg(args, '--workspace-level') || 'read_only';

  if (!WORKSPACE_LEVELS.has(workspaceLevel)) {
    outputError('INVALID_WORKSPACE_LEVEL', 'workspace level must be one of: none, read_only, controlled_runtime_consumer, workspace_first', {
      received: workspaceLevel
    });
    process.exit(1);
  }
  if ((workspaceLevel === 'controlled_runtime_consumer' || workspaceLevel === 'workspace_first') && !hasWorkspaceGovernanceSquad()) {
    outputError(
      'MISSING_C_LEVEL',
      'controlled_runtime_consumer and workspace_first require squads/c-level to exist',
      { received: workspaceLevel }
    );
    process.exit(1);
  }
  const displayName = argName ||
    (state && state.display_name) ||
    slug.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  const date = new Date().toISOString().split('T')[0];
  const squadDir = path.join(SQUADS_BASE, slug);
  const created = [];
  const skipped = [];

  // Create directories
  for (const dir of DIRECTORIES) {
    const dirPath = path.join(squadDir, dir);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      // Create .gitkeep
      fs.writeFileSync(path.join(dirPath, '.gitkeep'), '');
      created.push(`${dir}/`);
    } else {
      skipped.push(`${dir}/`);
    }
  }

  // Create README.md
  const readmePath = path.join(squadDir, 'README.md');
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(readmePath, getReadmeTemplate(slug, displayName, date, workspaceLevel));
    created.push('README.md');
  } else {
    skipped.push('README.md');
  }

  // Create config.yaml
  const configPath = path.join(squadDir, 'config.yaml');
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, getConfigTemplate(slug, displayName, date, workspaceLevel));
    created.push('config.yaml');
  } else {
    skipped.push('config.yaml');
  }

  outputJson({
    success: true,
    slug,
    display_name: displayName,
    workspace_level: workspaceLevel,
    path: squadDir,
    created,
    skipped,
    message: created.length > 0
      ? `Created ${created.length} items`
      : 'Structure already exists'
  });
}

main();
