#!/usr/bin/env python3
import os
import glob
import yaml
import sys

# Diretórios
import subprocess
BASE_DIR = subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
MINDS_DIR = os.path.join(BASE_DIR, "squads/squad-creator-pro/minds")
OUT_FILE = os.path.join(BASE_DIR, ".aiox-core/governance/heuristic-registry.yaml")

registry = {
    "heuristic_registry": {
        "version": "1.0",
        "description": "Unified Cross-Mind Heuristic Database. Auto-generated by build pipeline.",
        "heuristics": []
    }
}

count = 0

for mind in os.listdir(MINDS_DIR):
    mind_path = os.path.join(MINDS_DIR, mind, "heuristics")
    if not os.path.isdir(mind_path): continue
        
    for fpath in glob.glob(os.path.join(mind_path, "*.md")):
        h_id = os.path.basename(fpath).replace(".md", "")
        
        try:
            with open(fpath, "r", encoding="utf-8") as file:
                content = file.read()
        except:
            continue
        
        # Extract YAML Frontmatter
        fm = {}
        if content.startswith("---"):
            parts = content.split("---", 2)
            if len(parts) >= 3:
                try:
                    fm = yaml.safe_load(parts[1]) or {}
                except Exception as e:
                    print(f"Warning: could not parse frontmatter in {h_id}: {e}")
        
        # Extract title and zone globally if missed by Frontmatter
        title = fm.get('title', h_id)
        zone = "unknown"
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("title:"):
                title = line.replace("title:", "").replace('"', "").strip()
            elif line.startswith('zone:'):
                zone = line.replace("zone:", "").replace('"', "").strip()
            elif line.startswith("**Zone:**"):
                zone = line.split("**Zone:**")[1].strip()
        
        cross_map = fm.get('cross_mind_map', {})
        
        entry = {
            "id": h_id,
            "title": title,
            "mind": mind,
            "zone": zone
        }
        
        # Attach associative mappings if they exist
        if cross_map:
            entry["cross_mind_map"] = cross_map
            
        registry["heuristic_registry"]["heuristics"].append(entry)
        count += 1

# Sort for deterministic output
registry["heuristic_registry"]["heuristics"].sort(key=lambda x: x["id"])

# Write Canonical Registry
os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
with open(OUT_FILE, "w", encoding="utf-8") as out:
    yaml.dump(registry, out, default_flow_style=False, sort_keys=False, allow_unicode=True)

print(f"[OK] Generated {OUT_FILE}")
print(f"[OK] Total registered heuristics configured with Governance: {count}")
